#===== Database Configuration =====
# PostgreSQL settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Tasks
spring.datasource.username=postgres
spring.datasource.password=1234

# Schema (optional)
spring.jpa.properties.hibernate.default_schema=public

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# Server
server.port=8080